# Generated by Django 3.2.5 on 2021-07-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='management_employee',
            name='emp_id',
            field=models.IntegerField(null=True),
        ),
    ]
